; PlatformIO Project Configuration File
;
; Copyright (C) 2026 Dmitry Korobkov <dmitry.korobkov.nn@gmail.com>
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.

[env:board-esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags =
	-std=c++2a
	-D SERIAL_BAUD_RATE=74880
	-D LOG_LEVEL=5
build_unflags =
	-std=gnu++17
upload_speed = 115200
monitor_speed = 74880
test_speed = 74880
monitor_filters = default
	esp8266_exception_decoder
	time
monitor_rts = 0
monitor_dtr = 0

test_framework = unity
test_build_src = true
